### ISSUE TITLE
SIGSEGV using hpipm

### ISSUE THREAD

**Issue by MiriSalj** [giaf/blasfeo#138]
Hi guys, 

I hope this is the right place for this issue. 
Since a couple of days I'm struggling with hpipm. The example runs perfectly fine but
when using hpipm for my particular ocp I get the following error:

Program received signal SIGSEGV, Segmentation fault.
0x00005555558aaf87 in d_ocp_qp_init_var ()

Does anyone know how to deal with that? I appreciate any help.

Thanks a lot.
Best, Miri

**Comment by giaf** [comment]
Hi Miri,

I would need a bit more information in order to be able to help you.
First of all, why do you open the issue on the BLASFEO repository instead of the HPIPM one? Is the segmentation fault happening at a line where a BLASFEO routine is called?
Knowing the exact source code line where the issue happens would already provide some useful hint.

Without having more information, I would suspect the issue to be on your side, maybe some structure not initialized, or some mismatch between the sizes (N, nx, nu, ...) of different structures.
