### ISSUE TITLE
MacOS M2 compiling issue

### ISSUE THREAD

**Issue by shbang91** [giaf/blasfeo#170]
Hello,

Thanks for maintaining this nice repo!

I have an issue compiling blasfeo in my M2 Mac. 
Following the instruction, I've changed the architecture `target` to `ARMV8A_APPLE_M1` in `Makefile.rule` and I used the Clang as my c compiler as shown below:
<img width="416" alt="image" src="https://github.com/giaf/blasfeo/assets/42048897/04c9004c-46e6-4163-89f0-45ed02e3c8b0">

I got an error when I triggered `make shared_library -j12` as follows:
<img width="1070" alt="image" src="https://github.com/giaf/blasfeo/assets/42048897/79b01a32-02de-497a-a421-8d21d51ddc2f">

Do you have any idea on how to resolve this issue?

Thank you.

**Comment by giaf** [comment]
Mac devices with M1 and M2 processors (ARMv8A architecture) can also run x86_64 executables, that are instantly translating them to the ARMv8A instruction set used by the processor by the Rosetta software.

In your case, you can see that the target of your compiler is x86_64, so it is not producing native ARMv8A code but x86_64 code.
If you want to use that compiler, you should choose a x86_64 target in BLASFEO (e.g. Haswell).

However, for best performance, if possible you should switch to a compiler targeting the ARMv8A architecture (and use it to compile your entire application, not only BLASFEO), such that native ARMv8A code can be executed directly by the processor, instead of having x86_64 code being translated first.

**Comment by shbang91** [comment]
I appreciate your help! 
I successfully changed the compiler to the ARM architecture and built the blasfeo and hpipm.
